import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "HULT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"w-full"}>
        {/* {children} */}
        <header>
          <Header />
        </header>
        <div className="mt-20">{children}</div>
      </body>
    </html>
  );
}
