import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "HULT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">       
      <body
        className={''}
      >
        <header>
        <Header/>
        </header>
        <main className=" mt-12 h-[1000px]">
          {children}
        </main>
        <footer className="bg-black text-white">
          <Footer/>
        </footer>
      
      </body>
 
    </html>
  );
}
