export const team = [
    {
      name: "Samikshya Ghimire",
      position: "Campus Director",
      img_link: "/Samikshya.png",
      facebook: "https://www.facebook.com/samikshyaxx?mibextid=LQQJ4d",
      instagram: "https://www.instagram.com/samikshyaxx/",
      lindedin: "https://www.linkedin.com/in/samikshya-ghimire-2222222xx/",
      twitter: "#",
    },
    {
      name: "Simon Khadka",
      position: "Deputy Campus Director",
      img_link: "/Simon.png",
      facebook: "#",
      instagram: "https://www.instagram.com/siimon.iii?igsh=aTlvdHU2aTV5b3A3",
      lindedin: "http://linkedin.com/in/simon-khadka-627b4a323",
      twitter: "#",
    },
    {
      name: "Sujal Bikram Thapa",
      position: "Program Director",
      img_link: "Sujal.png",
      facebook: "https://www.facebook.com/sujalbikramthapa",
      instagram: "https://www.instagram.com/sujalbthapa/",
      lindedin: "https://www.linkedin.com/in/sujalbthapa/",
      twitter: "https://twitter.com/sujalbikramth",
    },
    {
      name: "Nabin Paudel",
      position: "Technical Coordinator",
      img_link: "Nabin.png",
      facebook: " https://www.facebook.com/nabin.paudel.41",
      instagram: " https://www.instagram.com/nabin_paudel24/",
      lindedin: "https://np.linkedin.com/in/nabin-paudel-133902293",
      twitter: " https://github.com/NabinPaudel001",
    },
    {
      name: "Nishan Paudel",
      position: "Academic Coordinator",
      img_link: "/Nishan.png",
      facebook: "https://www.facebook.com/nishan.paudel.2061?mibextid=ZbWKwL ",
      instagram: "https://www.instagram.com/neezpau/",
      lindedin: "https://www.linkedin.com/in/nishanpaudel2004?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app ",
      twitter: "https://x.com/neezpau2004?t=wBQ7pHFGZUc3W3SqJbwPWw&s=09",
    },
    {
      name: "Anish Kumar Neupane",
      position: "Logistic Coordinator",
      img_link: "/Anish.png",
      facebook: "https://www.facebook.com/anishkn04",
      instagram: "https://www.instagram.com/anishkn04",
      lindedin: "https://www.linkedin.com/in/anishkn04/",
      twitter: "https://x.com/anishkn04",
    },
    {
      name: "Abhaya Bhatta",
      position: "Sponsor Coordinator",
      img_link: "/Abhaya.png",
      facebook: "https://www.facebook.com/abhayabhatta.010",
      instagram: "https://www.instagram.com/abhaya._.b/",
      lindedin: "https://www.linkedin.com/in/abhayab/ ",
      twitter: "#",
    },
    {
      name: "Oscar Giri",
      position: "Outreach Coordinator",
      img_link: "/Oscar.png",
      facebook: "https://www.facebook.com/chelsea.oscar.16940?mibextid=LQQJ4d",
      instagram: "https://www.instagram.com/osc.aar",
      lindedin: "https://www.linkedin.com/in/oscar-giri-1309bb301",
      twitter: "#",
    },
    {
      name: "Prayush Bhandar",
      position: "Startup Coordinator",
      img_link: "/prayush.png",
      facebook: "https://www.facebook.com/pra.yush.50?mibextid=ZbWKwL",
      instagram: "https://www.instagram.com/pra_yush60/",
      lindedin: "https://www.linkedin.com/in/samikshya-ghimire-2222222xx/",
      twitter: "https://x.com/BhandariPrayush?t=OgymbWFhr7ZsCg4q8Oc4ow&s=09",
    },
    {
      name: "Prashubha Pathak",
      position: "Media Coordinator",
      img_link: "/prashubha.png",
      facebook: "https://www.facebook.com/share/14kqPrDAx5/",
      instagram: "https://www.instagram.com/prashubha_pathak?igsh=eGpubTdoMTA0bWVh",
      lindedin: "https://www.linkedin.com/in/prashubha-pathak-1077a32b2?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      twitter: "#",
    },
    {
      name: "Aman Sheikh",
      position: "Technical Member",
      img_link: "/Aman.png",
      facebook: "https://www.facebook.com/fried.donutslinger",
      instagram: "https://www.instagram.com/sheikh_a_man/",
      lindedin: "https://www.linkedin.com/in/aman-sheikh-044b6a155/",
      twitter: "#",
    },
    {
      name: "Rushab Risal",
      position: "Technical Member",
      img_link: "/Rushab.png",
      facebook: "https://www.facebook.com/profile.php?id=100075602340579",
      instagram: "https://www.instagram.com/risalrushab/",
      lindedin: "https://www.linkedin.com/in/rushabofficials/",
      twitter: "#",
    },
    {
      name: "Nisha Singh",
      position: " Outreach/Sponsorship member ",
      img_link: "/Nisha.png",
      facebook: "https://www.facebook.com/profile.php?id=100091953543551&mibextid=ZbWKwL",
      instagram: "#",
      lindedin: "#",
      twitter: "#",
    },
    {
      name: "Prashanta Rokaya",
      position: "Logistics Member",
      img_link: "/Prashanta.png",
      facebook: "https://www.facebook.com/prashant.chhetri.77777",
      instagram: "https://www.instagram.com/prashant_chhetri07/",
      lindedin: "https://www.linkedin.com/in/prashant-chhetri-4867a62b6/",
      twitter: "https://x.com/PChhetrii84813?t=H_tyQ2W3QtIYr2rngCjiDw&s=07",
    },

    {
      name: "Sushant Adhikari",
      position: "Logistics Member",
      img_link: "/Sushant.png",
      facebook: "https://www.facebook.com/profile.php?id=100068563911770&mibextid=ZbWKwL",
      instagram: "https://www.instagram.com/_sushant7_7/",
      lindedin: "https://www.linkedin.com/in/sushant-adhikari-6694a8212?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      twitter: "#",
    },
      
    {
      name: "Pushpa Sah",
      position: "Volunteer",
      img_link: "/Puspa.png",
      facebook: "https://www.facebook.com/pushpa.shah.9469545",
      instagram: "https://www.instagram.com/pushpasah_07/",
      lindedin: "#",
      twitter: "#",
    },
  ];
 